### PR TITLE
Fix detection of control statements

### LINKED ISSUE #33: Detection of variable names as control statements e.g. 'return_x' treated as 'return'
What the code looks like before pressing `enter`:

```python
def my_example():
    return_x = 1|
```

What I want the code to look like after pressing `enter`:

```python
def my_example():
    return_x = 1
    |
```

What the code actually looks like after pressing `enter`:

```python
def my_example():
    return_x = 1
|
```

The section in parseLines looks for dedentNextKeywords by using startswith() but that would allow any variable name starting with "return", "pass", "break", "continue" or "raise" to be counted as a keyword and the resulting dedent would be incorrect. I will submit a pull request shortly.

**Environment (please complete the following information):**
 - `Python Indent` version: [e.g. 1.1.0]
 - Visual Studio Code version: [e.g. 1.36.1]
 - OS: Windows 10 1809

### PR DESCRIPTION
**Pull request by WhistleWhileYouWork**
Fixes #33 
I split the test for dedentNextKeywords into 2 tests, 1 for where the statement is on a line by itself and one for "return " and "raise " since they can have arguments that come after.

### CODE REVIEW

**Comment by kbrose** [comment]
Hey @WhistleWhileYouWork, thanks for the PR! I took your idea and reworked it as a list of regexes which test for word boundaries on the keywords. I felt this was easier to maintain than two separate lists of keywords with some overlap. See #36.

Some other comments:

* All the extra commits meant I couldn't rebase the commits on top of my master branch. Make sure you pull from my master branch before starting a feature branch. https://help.github.com/en/articles/fork-a-repo seems like a good resource to learn more.
* When adding fixes like this, it's important to add a test to make sure we don't accidentally break the functionality in the future.

**Comment by WhistleWhileYouWork** [comment]
Hi, @kbrose. Cool, regex keeps things simpler but is something I shy away from myself.

Using git in a collaborative manner is still an enigma for me (this is only my 3rd PR). I actually already followed those instructions and it's sub-links to merge your changes into mine first. via:
    git fetch upstream
    git checkout master
    git merge upstream/master
    git push origin master
But obviously this didn't work. The commit said "Merge remote-tracking branch 'upstream/master'" but the master branch still said "This branch is 8 commits ahead,... kbrose:master." I think the problem was I didn't create a separate branch before I made changes and a PR so all changes were on master? I only remembered to create a new branch for this PR but the damage was already done.

I would have added tests, but I don't do Typescript/Javascript, just python. I'll just stick with filing issues with some suggested code changes. Thanks for your patience and help!

**Comment by kbrose** [comment]
Ah, I definitely appreciate your PRs. I'll take a PR that gets me 90% of the way there over just an issue every single time. If you're willing, I'd be more than happy to continue reviewing your additions. But obviously you should do what you're comfortable with -- it's all volunteer work after all.

Looking at your flow description, I agree with your diagnosis. The extra commits on master were likely your issue.

If I've messed up my master branch in this way (which happens very often), I do this:

```bash
# make sure we're on master
git checkout master

# make sure I've got the latest from upstream
git fetch --all

# WARNING: This will remove any commits you have on your local master branch!
#          Backup your work if you need to!
git reset --hard upstream/master

# SUPER EXTRA WARNING: This will force GitHub's copy of the repo to match,
#                      meaning you cannot recover your previous state.
git push --force

# Create feature branch, work as normal, etc.
```

When looking at your fork's page on GitHub, you should then see

> This branch is even with kbrose:master

Re: Tests, I similarly only really code in Python. I actually first wrote javascript to [help write this same kind of extension for Atom](https://github.com/DSpeckhals/python-indent/pull/9). And I haven't written javascript/typescript since except to write this extension.

But I've been surprised how easy the tests are to develop. All of the tests I've written recently have been copy/pastes with minor editing from https://github.com/kbrose/vsc-python-indent/blob/master/src/test/extension.test.ts

**Comment by WhistleWhileYouWork** [comment]
OK. I'll submit more PRs and I'll look into tests for JS. I think my main hangup is setting up a dev environment for JS and VSCode extensions. I should take a few hours and adjust to the idiosyncrasies. I dabble occasionally, I just hate the syntax! All those curly braces and semicolons make me want to throw up.

Thanks for the git help. I ended up renaming the last commit you made (just before I starting making my commits) back to `master`. Then I synced. Everything is back to _even_ and I managed to preserve my old commits on the errant branch too. Reading up on how to do it (there were plenty of options) made my head spin. I'll hold on to your tip as well for future use. Thanks.

**Pull request closed without merging**
